version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: zenika/terraform-aws-cli:release-6.0_terraform-0.15.5_awscli-1.27.60
    steps:
      - checkout
      - run:
          name: Create infrastructure on AWS
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            cd terraform-files/infrastructure/
            terraform init
            terraform plan
            terraform apply --auto-approve